version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@uifabric/icons"
    versions:
    - 7.5.17
    - 7.5.21
    - 7.5.22
  - dependency-name: "@uifabric/styling"
    versions:
    - 7.16.19
    - 7.18.0
    - 7.18.1
  - dependency-name: got
    versions:
    - 11.8.1
